on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/*
      - workflow/*

jobs:
  build_fw:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v5.3
    steps:
      - name: "Checkout files"
        uses: actions/checkout@v4
      - name: "Regular firmware build"
        run: "./ci/build.sh"
